import sys
import peppy
import glob

subworkflow tidal_wf:
    workdir:
        "../subworkflows/tetf_tidal/"
    snakefile:
        "../subworkflows/tetf_tidal/workflow/Snakefile"

subworkflow refs_wf:
    workdir:
        "../subworkflows/tetf_refs/"
    snakefile:
        "../subworkflows/tetf_refs/workflow/Snakefile"

subworkflow wgs_wf:
    workdir:
        "../subworkflows/tetf_dgrp_wgs/"
    snakefile:
        "../subworkflows/tetf_dgrp_wgs/workflow/Snakefile"

subworkflow dgrp_coex_wf:
    workdir:
        "../subworkflows/tetf_lm_coex/"
    snakefile:
        "../subworkflows/tetf_lm_coex/workflow/Snakefile"

subworkflow dgrp_quant_wf:
    workdir:
        "../subworkflows/tetf_expression_quant/"
    snakefile:
        "../subworkflows/tetf_expression_quant/workflow/Snakefile"

subworkflow dgrp_coex_d2_wf:
    workdir:
        "../subworkflows/tetf_lm_coex_dataset2/"
    snakefile:
        "../subworkflows/tetf_lm_coex_dataset2/workflow/Snakefile"

subworkflow tfrnai_wf:
    workdir:
        "../subworkflows/tetf_tfrnai/"
    snakefile:
        "../subworkflows/tetf_tfrnai/workflow/Snakefile"

subworkflow kd_rna_wf:
    workdir:
        "../subworkflows/tetf_kd/"
    snakefile:
        "../subworkflows/tetf_kd/workflow/Snakefile"

subworkflow calderon22_wf:
    workdir:
        "../subworkflows/tetf_calderon22/"
    snakefile:
        "../subworkflows/tetf_calderon22/workflow/Snakefile"

subworkflow basic_chip_wf:
    workdir:
        "../subworkflows/tetf_basic_chip/"
    snakefile:
        "../subworkflows/tetf_basic_chip/workflow/Snakefile"

subworkflow unr_ripseq_wf:
    workdir:
        "../subworkflows/tetf_ripseq/"
    snakefile:
        "../subworkflows/tetf_ripseq/workflow/Snakefile"

include: "rules/bundle.smk"


rule all:
    input:
        rules.bundle_refs_results.output,
        rules.bundle_lm_results.output,
        rules.bundle_dataset2_lm_results.output,
        rules.bundle_wgs_results.output,
        rules.bundle_kd_results.output,
        rules.bundle_3rd_party_tfrnai_results.output,
        rules.bundle_calderon22_results.output,
        rules.bundle_basic_chipseq_results.output,
        rules.bundle_tidal_results.output,
        rules.bundle_csem_chipseq_results.output,
        rules.bundle_unr_ripseq_results.output,
